-- MySQL Script generated by MySQL Workbench
-- Sat Jan 29 00:11:57 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema celke
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `celke` ;

-- -----------------------------------------------------
-- Schema celke
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `celke` DEFAULT CHARACTER SET utf8 ;
USE `celke` ;

-- -----------------------------------------------------
-- Table `celke`.`homes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `celke`.`homes` ;

CREATE TABLE IF NOT EXISTS `celke`.`homes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(13) NULL DEFAULT 'Null',
  `data_nascimento` VARCHAR(10) NULL DEFAULT 'Null',
  `cidade` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `endereco` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
